### ISSUE TITLE
[Bug, P3, #NFT] NFTs with broken GIFs tracking thread

### ISSUE THREAD

**Issue by conlan** [cryptovoxels/issues#52]
These NFT gifs currently display broken. In some cases like the Mlibty, other editions of the same token still work.

John McAfee - Decentral Eyes - Variant 02
by Coldie
- [x] https://opensea.io/assets/0xd2eca00493ea1218a7ad20009ac0a4602839ca2b/2

1906 KY01
by Brad Damico
- [x] https://opensea.io/assets/0xfbeef911dc5821886e1dda71586d90ed28174b7d/65651

Godzilla is not a threat to the Devcon
by Mlibty
- [x] https://opensea.io/assets/0xfbeef911dc5821886e1dda71586d90ed28174b7d/80612

Parcel demonstrating issue:
https://www.cryptovoxels.com/play?coords=N@372E,113N

![broken](https://user-images.githubusercontent.com/79074/68082957-eeefce00-fdd7-11e9-9702-e509dea10040.gif)

**Comment by WXTux** [comment]
These animated GIFs are not animated properly in Cryptovoxels

THEGODTANU from the MemoryChain Collection (broken animation)
[https://i.imgur.com/0yGv9td.gif](url)

Shy by Molly Soda - Digital Objects - GIF version (no animation)
[https://i.imgur.com/bfZayJ6.gif](url)

Parcel:
[https://www.cryptovoxels.com/play?coords=NE@305W,220S](url)

**Comment by mlibty** [comment]
Two NFT not loading,one image, another gif:  https://www.cryptovoxels.com/play?coords=N@246E,337S&debug=true&ui=html

**Comment by Uwe2019** [comment]
My last acquired art work by Ophelia Fu - gif is not displayed 
![notworking](https://user-images.githubusercontent.com/45010573/68472124-19021f80-0220-11ea-82b9-ade8c76f8502.png)
https://www.cryptovoxels.com/play?coords=E@128E,3U,216S

**Comment by conlan** [comment]
Hey @everyone in this thread, ben pushed an update and it looks like some of the gifs were fixed. Can you guys check your NFTs?

**Comment by conlan** [comment]
Both THEGODTANU and Shy by Molly Soda appear to be fixed and animated:
<img width="527" alt="Screen Shot 2019-11-10 at 10 42 40 PM" src="https://user-images.githubusercontent.com/79074/68566574-96d64e80-040b-11ea-95e6-fa4fded1cf6a.png">
<img width="523" alt="Screen Shot 2019-11-10 at 10 42 34 PM" src="https://user-images.githubusercontent.com/79074/68566580-99d13f00-040b-11ea-8451-38ef405c37a5.png">

**Comment by conlan** [comment]
mlibty's appear fixed but maybe I'm missing where the broken one was?

<img width="1574" alt="Screen Shot 2019-11-10 at 10 49 14 PM" src="https://user-images.githubusercontent.com/79074/68566900-807cc280-040c-11ea-92f3-f6bb8ee089e5.png">
<img width="1624" alt="Screen Shot 2019-11-10 at 10 49 00 PM" src="https://user-images.githubusercontent.com/79074/68566904-82468600-040c-11ea-956a-5c6c27e49e32.png">

**Comment by conlan** [comment]
Ophelia Fu's and the Brad Damico appear to be the last 2 broken gifs:

https://opensea.io/assets/0xfbeef911dc5821886e1dda71586d90ed28174b7d/80112
https://opensea.io/assets/0xfbeef911dc5821886e1dda71586d90ed28174b7d/65651

**Comment by mlibty** [comment]
Yes, tested the pieces also on other plots and all working!!!!! THX!!!!

**Comment by conlan** [comment]
Okay verified that "1906 KY01" is now working.

"Falling Petals" is the last remaining broken item on this list: 
- [ ] https://opensea.io/assets/0xfbeef911dc5821886e1dda71586d90ed28174b7d/80112

https://www.cryptovoxels.com/play?coords=E@129E,3U,216S

**Comment by Alotta-Money** [comment]
Hi there, same problem with St Nakamoto :
https://opensea.io/assets/0xb932a70a57673d89f4acffbe830e8ed7f75fb9e0/5624
Big Brother :
https://opensea.io/assets/0xb932a70a57673d89f4acffbe830e8ed7f75fb9e0/5503

**Comment by bnolan** [comment]
Is this fixed? I'm pretty sure I fixed this - please reopen if any of the NFTs aren't displaying correctly. :)
